import Header from "@/components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us",
  description: "Who runs Moments Gallari, where the prompts come from, and how the collection is put together.",
  alternates: { canonical: "/about" },
};

/**
 * NOTE ON E-E-A-T: this page deliberately contains no placeholders and invents
 * nothing — no team, no company, no city, no founding year. Everything asserted
 * here is verifiable: the Instagram account, the contact address, and the nature
 * of the collection.
 *
 * Adding a real full name and location would strengthen the page further, and is
 * worth doing. Do NOT substitute an invented one: fabricated identity is what the
 * old `author`/avatar system did, and it is a Publisher Policies
 * "Misrepresentation" issue rather than merely a quality one.
 */
export default function AboutPage() {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-900 dark:bg-[#000000] dark:text-white selection:bg-black/10 dark:selection:bg-white/30 relative overflow-x-hidden transition-colors duration-300">
      <Header />

      <div className="relative z-10 px-4 sm:px-6 pt-8 sm:pt-32 pb-24 max-w-3xl mx-auto">
        <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-8">About Moments Gallari</h1>

        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p className="lead">
            Moments Gallari is a small, independently run library of AI image
            prompts. It is not a company and not a team — it is one person
            publishing the prompts behind images they make.
          </p>

          <h2>Where the prompts come from</h2>
          <p>
            Every prompt on this site was written and first published by us on our
            own Instagram account,{" "}
            <a
              href="https://www.instagram.com/moments_galleri"
              target="_blank"
              rel="noopener noreferrer"
            >
              @moments_galleri
            </a>
            . Each prompt page links back to the original post, and the post is
            embedded there in full with its caption intact.
          </p>
          <p>
            Nothing here is scraped from other people. If you believe a prompt
            listed here originated with you, email us and it will be credited or
            removed.
          </p>

          <h2>How to read a prompt page</h2>
          <p>
            Each page carries the complete prompt text, free to copy and adapt, plus
            the tags describing the style it produces. Prompts are functional text
            rather than creative work and we make no ownership claim over them —
            take them, change them, use them commercially if you like.
          </p>
          <p>
            We are currently working through the collection and adding, for each
            prompt, our own generated image and a written account of what the prompt
            actually produced — including the parts that failed and the specific
            edits that fixed them. Pages that have not reached that stage say so
            plainly rather than padding the space with filler.
          </p>

          <h2>The images are AI-generated</h2>
          <p>
            Every image associated with this site is generated by an AI image model.
            None of it is photography, and none of it depicts real events. Where a
            prompt is designed around a reference photograph, we ask that you only
            use photographs you own or have permission to use.
          </p>

          <h2>What we don&apos;t do</h2>
          <p>
            We don&apos;t republish other people&apos;s generated images as our own.
            We don&apos;t publish invented contributor names — an earlier version of
            this site attached fictional author names and stock profile photos to
            each prompt, and those have been removed entirely.
          </p>

          <h2>How this site is funded</h2>
          <p>
            Moments Gallari is intended to be supported by display advertising. We
            have no commercial relationship with, and no affiliation to, Midjourney,
            Google, Stability AI, OpenAI or Meta.
          </p>

          <h2>Contact</h2>
          <p>
            Questions, corrections, attribution and takedown requests all go to the
            same place:{" "}
            <a href="mailto:dineshkumarmurugesan002@gmail.com" className="break-all">
              dineshkumarmurugesan002@gmail.com
            </a>
            . More detail is on the <a href="/contact">contact page</a>.
          </p>
        </div>
      </div>
    </main>
  );
}
